wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.16
    start_time: 1742587455
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.10.16
      5: 0.12.21
      8:
      - 5
action_range:
  desc: null
  value:
  - -5
  - 5
discount:
  desc: null
  value: 0.9
discretize_state_weight:
  desc: null
  value:
  - 5
  - 5
  - 5
  - 5
epsilon_decay:
  desc: null
  value: 0.9997
final_epsilon:
  desc: null
  value: 0.01
learning_rate:
  desc: null
  value: 0.3
n_episodes:
  desc: null
  value: 10000
num_of_action:
  desc: null
  value: 9
start_epsilon:
  desc: null
  value: 1.0
